# Generated by Django 4.2.6 on 2023-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('rang', models.CharField(max_length=50, verbose_name='Возрастной рейтинг')),
                ('article', models.IntegerField(max_length=50, verbose_name='Артикул')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('s_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('n_name', models.CharField(max_length=50, verbose_name='Ник-Нейм')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('favorite', models.IntegerField(verbose_name='Предпочтения')),
            ],
        ),
    ]
